<H1> **Introducci√≥n a Python para Big Data** : üéä

Este notebook te guiar√° a trav√©s de los conceptos fundamentales de Python y la librer√≠a Pandas, esenciales para el an√°lisis de datos.

<H3> 1. Primeros pasos con Python üÜé

Comenzaremos con los conceptos b√°sicos de Python, como la creaci√≥n de variables y la impresi√≥n de valores.

In [ ]:
# Asignaci√≥n y tipos de datos
a = 1 + 1
b = "Big Data"

# Imprimir variables en pantalla
print(a)
print(b)

<H3> 2. Manejo de datos con Pandas ‚õµ

Pandas es una librer√≠a fundamental para trabajar con datos tabulares. Un DataFrame de Pandas es una estructura similar a una hoja de c√°lculo, con filas y columnas.

Crear un DataFrame

Podemos crear un DataFrame a partir de listas de Python.

In [ ]:
# Listas de datos
lista_personajes = ['Luke Skywalker', 'C-3PO', 'Darth Vader']
lista_altura = [172, 167, 202]

# Crear el DataFrame
import pandas as pd

d_star_wars = pd.DataFrame({
    'personaje': lista_personajes,
    'altura': lista_altura
})

# Mostrar el DataFrame y sus tipos de datos
print(d_star_wars)
print("---")
print(d_star_wars.dtypes)

        personaje  altura
0  Luke Skywalker     172
1           C-3PO     167
2     Darth Vader     202
---
personaje    object
altura        int64
dtype: object

<H3> 3. Cargar y explorar un archivo ‚úà

En el mundo real, los datos rara vez se crean manualmente.
Veamos como cargar un archivo CSV directamente desde una URL.

In [ ]:
#Antes de comenzar tenemos que instalar la librer√≠a funpymodeling que me permite conocer informaci√≥n estad√≠stica de los datos
%%capture
!pip install funpymodeling

In [ ]:
# Cargar un archivo CSV desde una URL
url = 'https://raw.githubusercontent.com/fpineyro/homework-0/master/starwars.csv'
d_star_wars_url = pd.read_csv(url)

# Explorar el DataFrame
# Muestra las primeras 5 filas
print("Primeras 5 filas:")
print(d_star_wars_url.head(7))

# Muestra el n√∫mero de filas y columnas (filas, columnas)
print("\nDimensiones del DataFrame:")
print(d_star_wars_url.shape)

# Muestra un resumen estad√≠stico de las variables
# ¬°Aseg√∫rate de instalar esta librer√≠a antes!
# !pip install funpymodeling
from funpymodeling.exploratory import status
print("\nEstad√≠sticas del DataFrame:")
status(d_star_wars_url)

Primeras 5 filas:
                 name  height mass   hair_color   skin_color eye_color  \
0      Luke Skywalker   172.0   77        blond         fair      blue
1               C-3PO   167.0   75          NaN         gold    yellow
2               R2-D2    96.0   32          NaN  white, blue       red
3         Darth Vader   202.0  136         none        white    yellow
4         Leia Organa   150.0   49        brown        light     brown
5           Owen Lars   178.0  120  brown, grey        light      blue
6  Beru Whitesun lars   165.0   75        brown        light      blue

  birth_year  gender homeworld species
0      19BBY    male  Tatooine   Human
1     112BBY     NaN  Tatooine   Droid
2      33BBY     NaN     Naboo   Droid
3    41.9BBY    male  Tatooine   Human
4      19BBY  female  Alderaan   Human
5      52BBY    male  Tatooine   Human
6      47BBY  female  Tatooine   Human

Dimensiones del DataFrame:
(87, 10)

ModuleNotFoundError: No module named 'funpymodeling'

<H3>4. Filtrar y seleccionar datos ‚õ≥

Para seleccionar datos espec√≠ficos de tu DataFrame, usa loc. Con loc puedes seleccionar filas y columnas por sus nombres o etiquetas.


El formato loc[filas, columnas] te permite seleccionar datos usando las etiquetas de filas y columnas.

[0, :]: El primer valor (0) selecciona la fila con la etiqueta 0. Los dos puntos (:) significan todas las columnas.

[:, 'nombre_columna']: Los dos puntos (:) seleccionan todas las filas. El nombre de la columna selecciona una columna espec√≠fica.

4.1. Seleccionar columnas

In [ ]:
# Seleccionar una sola columna
#d_star_wars['personaje']

# Seleccionar m√∫ltiples columnas
d_star_wars[['personaje', 'altura']]

4.2. Seleccionar filas

Podemos seleccionar filas bas√°ndote en su posici√≥n (√≠ndice).

Nota: el uso de 0:2 en loc es inclusivo, lo que significa que incluye los √≠ndices 0, 1 y 2.

In [ ]:
# Seleccionar la primera fila
d_star_wars.loc[0, :]

In [ ]:
# Seleccionar las 3 primeras filas
d_star_wars.loc[0:2, :]

4.3. Filtrar con condiciones

Podemos usar una condici√≥n para filtrar filas que cumplan con un criterio espec√≠fico. Por ejemplo, encontrar todos los personajes cuya altura sea mayor que 200.

In [ ]:
# Crear un filtro (devuelve True/False para cada fila)
filtro_altura = d_star_wars['altura'] > 200

# Aplicar el filtro para obtener solo los registros que cumplen la condici√≥n
d_star_wars.loc[filtro_altura, :]

4.4. Reemplazar valores

Podemos combinar el filtrado con la asignaci√≥n para cambiar valores espec√≠ficos en el DataFrame.

In [ ]:
# Reemplazar la altura de Darth Vader por 185
d_star_wars.loc[d_star_wars['personaje'] == 'Darth Vader', 'altura'] = 185

# Verificar el cambio
print(d_star_wars.loc[d_star_wars['personaje'] == 'Darth Vader', :])

<H3>5. Manejar valores nulos (NaN) ‚õé

5.1. Los valores faltantes (NaN) son muy comunes. Es crucial saber c√≥mo identificarlos y manejarlos.

In [ ]:
# Identificar nulos por columna
print("N√∫mero de nulos en cada columna:")
print(d_star_wars_url.isnull().sum())

In [ ]:
d_star_wars_url

In [ ]:
# Reemplazar valores nulos en columnas categ√≥ricas
valores_a_rellenar = {'homeworld': 'nulo_world', 'species': 'nulo_species'}

d_star_wars_url.fillna(value=valores_a_rellenar, inplace=True)
print(d_star_wars_url)

In [ ]:
#Vemos cual es el promedio de altura
print(d_star_wars_url['height'].mean())

In [ ]:
# Reemplazar valores nulos en columnas num√©ricas con el promedio
promedio_altura = d_star_wars_url['height'].mean()


d_star_wars_url['height'] = d_star_wars_url['height'].fillna(promedio_altura)
d_star_wars_url

In [ ]:
# Verificar que los nulos fueron reemplazados
status(d_star_wars_url['height'])

5.2. Eliminar registros con valores nulos
A veces, en lugar de reemplazar los valores nulos, lo mejor es eliminar por completo las filas o columnas que los contienen. El m√©todo dropna() de Pandas te permite hacerlo f√°cilmente.

Por defecto, dropna() elimina cualquier fila que contenga al menos un valor nulo. Es una forma r√°pida de limpiar el conjunto de datos si las filas con valores faltantes no son importantes para tu an√°lisis.

In [ ]:
# Eliminar las filas con valores nulos
d_star_wars_url.dropna(inplace=True)
status(d_star_wars_url)

<H3> 6. Crear nuevas columnas üõã

Puedes crear una nueva columna en un DataFrame y asignarle valores basados en una condici√≥n. Es una forma muy poderosa de derivar informaci√≥n a partir de los datos existentes.

In [ ]:
# Asignamos True si la altura es > 180, de lo contrario, False
d_star_wars['is_tall'] = d_star_wars['altura'] > 180

# Muestra el DataFrame con la nueva columna
print(d_star_wars)

<H3> 7. Copiar un DataFrame ¬©

Cuando realizas cambios en un DataFrame y quieres conservar la versi√≥n original, es una buena pr√°ctica hacer una copia. Esto te permite manipular la nueva versi√≥n sin afectar la original.

In [ ]:
#Hacer una copia del DataFrame
d_star_wars_copy = d_star_wars.copy()

# Ahora puedes trabajar con d_star_wars_copy sin afectar el original
d_star_wars_copy

************************************************************************************

<H2> Ejercicios üî∞

Aqu√≠ hay una serie de ejercicios para aplicar lo que aprendiste. ¬°No te frustres si te toma tiempo! La pr√°ctica es la clave.

<H3> Ejercicio 1. Carga el archivo heart_disease.csv en un DataFrame llamado d_hd. URL: https://raw.githubusercontent.com/fpineyro/homework-0/master/heart_disease.csv

In [ ]:
##Ejercicio 1
import pandas as pd
d_hd = pd.read_csv('https://raw.githubusercontent.com/fpineyro/homework-0/master/heart_disease.csv')
d_hd

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease
0,63,male,1,145,233,1,2,150,0,2.3,3,0.0,6.0,0,0,no
1,67,male,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2,1,yes
2,67,male,4,120,229,0,2,129,1,2.6,2,2.0,7.0,1,1,yes
3,37,male,3,130,250,0,0,187,0,3.5,3,0.0,3.0,0,0,no
4,41,female,2,130,204,0,2,172,0,1.4,1,0.0,3.0,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,male,1,110,264,0,0,132,0,1.2,2,0.0,7.0,1,0,yes
299,68,male,4,144,193,1,0,141,0,3.4,2,2.0,7.0,2,0,yes
300,57,male,4,130,131,0,0,115,1,1.2,2,1.0,7.0,3,1,yes
301,57,female,2,130,236,0,2,174,0,0.0,2,1.0,3.0,1,0,yes
302,38,male,3,138,175,0,0,173,0,0.0,1,NaN,3.0,0,0,no

<H3> Ejercicio 2. Muestra los primeros 5 y los √∫ltimos 5 registros de d_hd.

In [ ]:
##Ejercicio 2
d_hd.head(5)
d_hd.tail(5)

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease
298,45,male,1,110,264,0,0,132,0,1.2,2,0.0,7.0,1,0,yes
299,68,male,4,144,193,1,0,141,0,3.4,2,2.0,7.0,2,0,yes
300,57,male,4,130,131,0,0,115,1,1.2,2,1.0,7.0,3,1,yes
301,57,female,2,130,236,0,2,174,0,0.0,2,1.0,3.0,1,0,yes
302,38,male,3,138,175,0,0,173,0,0.0,1,NaN,3.0,0,0,no

<H3> Ejercicio 3. Selecciona e imprime las columnas age y has_heart_disease.

In [ ]:
##Ejercicio 3
print(d_hd[['age', 'has_heart_disease']])

     age has_heart_disease
0     63                no
1     67               yes
2     67               yes
3     37                no
4     41                no
..   ...               ...
298   45               yes
299   68               yes
300   57               yes
301   57               yes
302   38                no

[303 rows x 2 columns]

<H3> Ejercicio 4. Crea un filtro para encontrar todos los registros donde colesterol (serum_cholestoral) sea mayor que 250.

In [ ]:
##Ejercicio 4
filtro_colesterol = d_hd['serum_cholestoral'] > 250
d_hd[filtro_colesterol]

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease
1,67,male,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2,1,yes
6,62,female,4,140,268,0,2,160,0,3.6,3,2.0,3.0,3,0,yes
7,57,female,4,120,354,0,0,163,1,0.6,1,0.0,3.0,0,1,no
8,63,male,4,130,254,0,2,147,0,1.4,2,1.0,7.0,2,0,yes
11,56,female,2,140,294,0,2,153,0,1.3,2,0.0,3.0,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,57,male,4,110,335,0,0,143,1,3.0,2,1.0,7.0,2,1,yes
281,47,male,3,130,253,0,0,179,0,0.0,1,0.0,3.0,0,0,no
285,58,male,4,114,318,0,1,140,0,4.4,3,3.0,6.0,4,0,yes
291,55,female,2,132,342,0,0,166,0,1.2,1,0.0,3.0,0,0,no
298,45,male,1,110,264,0,0,132,0,1.2,2,0.0,7.0,1,0,yes

<H3> Ejercicio 5. Usa la funci√≥n status() para identificar qu√© variables tienen valores nulos.

In [ ]:
##Ejercicio 5
d_hd.isnull().sum()

age                       0
gender                    0
chest_pain                0
resting_blood_pressure    0
serum_cholestoral         0
fasting_blood_sugar       0
resting_electro           0
max_heart_rate            0
exer_angina               0
oldpeak                   0
slope                     0
num_vessels_flour         4
thal                      0
heart_disease_severity    0
exter_angina              0
has_heart_disease         0
is_healthy                0
dtype: int64

<H3> Ejercicio 6. Reemplaza los valores nulos de la columna thal por un valor de 999.

In [ ]:
##Ejercicio 6
d_hd['thal'] = d_hd['thal'].fillna(999)
print(d_hd['thal'].isnull().sum())

0

<H3> Ejercicio 7. Filtrar por m√∫ltiples condiciones:

Utiliza el DataFrame d_hd y filtra para encontrar todos los registros de pacientes que tienen m√°s de 60 a√±os Y un nivel de colesterol (serum_cholestoral) superior a 250.

In [ ]:
##Ejercicio 7
filtro_edad = d_hd['age'] > 60
filtro_colesterol = d_hd['serum_cholestoral'] > 250
d_hd_filtrado = d_hd[filtro_edad & filtro_colesterol]
print(d_hd_filtrado)

     age  gender  chest_pain  resting_blood_pressure  serum_cholestoral  \
1     67    male           4                     160                286
6     62  female           4                     140                268
8     63    male           4                     130                254
32    64    male           3                     140                335
42    71  female           2                     160                302
44    61  female           4                     130                330
48    65  female           3                     140                417
70    65  female           3                     155                269
71    67    male           4                     125                254
72    62    male           4                     120                267
75    65  female           3                     160                360
83    68    male           3                     180                274
90    66    male           4                     120                302
94    63  female           3                     135                252
103   71  female           3                     110                265
108   61    male           4                     120                260
110   61  female           4                     145                307
114   62  female           3                     130                263
118   63    male           4                     130                330
119   65    male           4                     135                254
121   63  female           4                     150                407
124   65    male           1                     138                282
137   62    male           2                     120                281
143   64    male           3                     125                309
152   67  female           3                     115                564
155   70    male           4                     130                322
159   68    male           3                     118                277
161   77    male           4                     125                304
170   70    male           3                     160                269
173   62  female           4                     140                394
189   69    male           3                     140                254
193   62  female           4                     138                294
195   67    male           4                     100                299
201   64  female           4                     180                325
203   64  female           3                     140                313
218   64  female           4                     130                303
224   63  female           4                     108                269
227   67  female           3                     152                277
233   74  female           2                     120                269
252   64    male           4                     128                263
276   66  female           3                     146                278

     fasting_blood_sugar  resting_electro  max_heart_rate  exer_angina  \
1                      0                2             108            1
6                      0                2             160            0
8                      0                2             147            0
32                     0                0             158            0
42                     0                0             162            0
44                     0                2             169            0
48                     1                2             157            0
70                     0                0             148            0
71                     1                0             163            0
72                     0                0              99            1
75                     0                2             151            0
83                     1                2             150            1
90                     0                2             151            0
94                     0                2             172            0
103                    1                2             130            0
108                    0                0             140            1
110                    0                2             146            1
114                    0                0              97            0
118                    1                2             132            1
119                    0                2             127            0
121                    0                2             154            0
124                    1                2             174            0
137                    0                2             103            0
143                    0                0             131            1
152                    0                2             160            0
155                    0                2             109            0
159                    0                0             151            0
161                    0                2             162            1
170                    0                0             112            1
173                    0                2             157            0
189                    0                2             146            0
193                    1                0             106            0
195                    0                2             125            1
201                    0                0             154            1
203                    0                0             133            0
218                    0                0             122            0
224                    0                0             169            1
227                    0                0             172            0
233                    0                2             121            1
252                    0                0             105            1
276                    0                2             152            0

     oldpeak  slope  num_vessels_flour  thal  heart_disease_severity  \
1        1.5      2                3.0   3.0                       2
6        3.6      3                2.0   3.0                       3
8        1.4      2                1.0   7.0                       2
32       0.0      1                0.0   3.0                       1
42       0.4      1                2.0   3.0                       0
44       0.0      1                0.0   3.0                       1
48       0.8      1                1.0   3.0                       0
70       0.8      1                0.0   3.0                       0
71       0.2      2                2.0   7.0                       3
72       1.8      2                2.0   7.0                       1
75       0.8      1                0.0   3.0                       0
83       1.6      2                0.0   7.0                       3
90       0.4      2                0.0   3.0                       0
94       0.0      1                0.0   3.0                       0
103      0.0      1                1.0   3.0                       0
108      3.6      2                1.0   7.0                       2
110      1.0      2                0.0   7.0                       1
114      1.2      2                1.0   7.0                       2
118      1.8      1                3.0   7.0                       3
119      2.8      2                1.0   7.0                       2
121      4.0      2                3.0   7.0                       4
124      1.4      2                1.0   3.0                       1
137      1.4      2                1.0   7.0                       3
143      1.8      2                0.0   7.0                       1
152      1.6      2                0.0   7.0                       0
155      2.4      2                3.0   3.0                       1
159      1.0      1                1.0   7.0                       0
161      0.0      1                3.0   3.0                       4
170      2.9      2                1.0   7.0                       3
173      1.2      2                0.0   3.0                       0
189      2.0      2                3.0   7.0                       2
193      1.9      2                3.0   3.0                       2
195      0.9      2                2.0   3.0                       3
201      0.0      1                0.0   3.0                       0
203      0.2      1                0.0   7.0                       0
218      2.0      2                2.0   3.0                       0
224      1.8      2                2.0   3.0                       1
227      0.0      1                1.0   3.0                       0
233      0.2      1                1.0   3.0                       0
252      0.2      2                1.0   7.0                       0
276      0.0      2                1.0   3.0                       0

     exter_angina has_heart_disease  is_healthy
1               1               yes       False
6               0               yes       False
8               0               yes       False
32              0               yes       False
42              0                no        True
44              0               yes       False
48              0                no        True
70              0                no        True
71              0               yes       False
72              1               yes       False
75              0                no        True
83              1               yes       False
90              0                no        True
94              0                no        True
103             0                no        True
108             1               yes       False
110             1               yes       False
114             0               yes       False
118             1               yes       False
119             0               yes       False
121             0               yes       False
124             0               yes       False
137             0               yes       False
143             1               yes       False
152             0                no        True
155             0               yes       False
159             0                no        True
161             1               yes       False
170             1               yes       False
173             0                no        True
189             0               yes       False
193             0               yes       False
195             1               yes       False
201             1                no        True
203             0                no        True
218             0                no        True
224             1               yes       False
227             0                no        True
233             1                no        True
252             1                no        True
276             0                no        True

<H3> Ejercicio 8. Reemplazar valores en una columna:

Selecciona la columna slope del DataFrame d_hd. Reemplaza el valor 1 por el string 'ascendente' y el valor 2 por 'descendente'. Muestra el resultado (no necesitas guardarlo en el DataFrame original).

In [ ]:
##Ejercicio 8
d_hd['slope'] = d_hd['slope'].replace({1: 'ascendente', 2: 'descendente'})
print(d_hd['slope'])

0                3
1      descendente
2      descendente
3                3
4       ascendente
          ...
298    descendente
299    descendente
300    descendente
301    descendente
302     ascendente
Name: slope, Length: 303, dtype: object

<H3>Ejercicio 9. Crear una nueva columna:

En el DataFrame d_hd, crea una nueva columna llamada is_healthy. Asigna el valor True si el paciente no tiene enfermedad del coraz√≥n (es decir, el valor en heart_disease_severity es 0) y False en caso contrario. Muestra el DataFrame con la nueva columna

In [ ]:
##Ejercicio 9
d_hd['is_healthy'] = d_hd['heart_disease_severity'] == 0
print(d_hd[['heart_disease_severity', 'is_healthy']])

     heart_disease_severity  is_healthy
0                         0        True
1                         2       False
2                         1       False
3                         0        True
4                         0        True
..                      ...         ...
298                       1       False
299                       2       False
300                       3       False
301                       1       False
302                       0        True

[303 rows x 2 columns]

<H3> Ejercicio 10. Eliminar registros con nulos:

Crea una copia del DataFrame d_hd llamada d_hd_clean. Usa el m√©todo dropna() para eliminar todos los registros que contengan al menos un valor nulo. Luego, usa status() para verificar que ya no hay valores nulos en d_hd_clean.

In [ ]:
##Ejercicio 10
from funpymodeling.exploratory import status
d_hd_clean = d_hd.copy()
d_hd_clean.dropna(inplace=True)
status(d_hd_clean)

ModuleNotFoundError: No module named 'funpymodeling'

************************************************************************************